version: '3'

services:
  sac-api:
    build:
      context: .
      dockerfile: dockerFiles/web.dockerfile
    
    expose:
        - 80
    
    depends_on:
      - sac-db
  
    environment:
      SAC_DB_HOST: sac-db
      SAC_DB_PORT: 3306
      SAC_DB_NAME: sac_web_api
      SAC_DB_USER: sac_web_api_ufjf
      SAC_DB_PASSWORD: s@cw3b4p1
      
  sac-db:
    build: 
      context: .
      dockerfile: dockerFiles/db.dockerfile

    # volumes:
    #   - ./database:/var/lib/mysql
    
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sac_web_api
      MYSQL_USER: sac_web_api_ufjf
      MYSQL_PASSWORD: s@cw3b4p1
